# Generated by Django 6.0.5 on 2026-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('periodo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
