# Generated by Django 6.0.5 on 2026-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('intensidad_horaria', models.IntegerField()),
                ('nivel', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
